Algoritmo "Venda"
// Escreva um algoritmo que receba o valor de um produto em reais e o
// desconto em porcentagem a ser oferecido na venda do produto.
// Informe o valor do desconto e o valor que o produto deverá ser vendido.
Var
vp, venp, desct: real




Inicio
escreval("Diga o valor do biscito Maria")
leia(vp)
desct <- vp/10
venp <- vp - desct
escreval("O desconto foi de, ", desct, " e vai ficar por ", venp)

Fimalgoritmo